defaultNamespace: oauth2-proxy
dependsOn:
helm:
  releaseName: oauth2-proxy
  chart: oauth2-proxy
  repo: https://oauth2-proxy.github.io/manifests
  version: "6.11.0"
targetCustomizations:
- name: rke2-2
  clusterSelector:
    matchLabels:
      provider.cattle.io: rke2
      topology.kubernetes.io/region: budapest
      topology.kubernetes.io/zone: esxi-sm4
      topology.kubernetes.io/cluster: rke2-2
  helm:
    valuesFiles:
      - rke2.yaml