# Oauth client configuration specifics
config:
  # OAuth client ID
  # clientID: "oauth2-proxy"
  # OAuth client secret
  # clientSecret: "{{ lookup('ipa', 'dex_secret', service='common/dummyforvault.{{ ipa_domain }}@{{ ipa_domain | upper }}') }}"
  # cookieSecret: "{{ lookup('ipa', 'oauth2_proxy_cookie', service='common/dummyforvault.{{ ipa_domain }}@{{ ipa_domain | upper }}') }}"
  existingSecret: oauth2-proxy-secret
  configFile: |-
    email_domains = [ "*" ]
    whitelist_domains = [ ".hackathon.marthy.xyz" ]
    cookie_domains = [ ".hackathon.marthy.xyz" ]
    upstreams = [ "file:///dev/null" ]
    pass_basic_auth = false
    pass_access_token = true
    set_authorization_header = true
    pass_authorization_header = true
    skip_provider_button = true
    provider = "azure"
    azure_tenant = "123c73da-4266-432d-a561-5452cb07ee8a"
    oidc_issuer_url = "https://login.microsoftonline.com/123c73da-4266-432d-a561-5452cb07ee8a/v2.0"
    allowed_groups = "ERFIDO"
htpasswdFile:
  enabled: false

service:
  type: ClusterIP
  portNumber: 80
  annotations: {}
resources:
  limits:
    cpu: 100m
    memory: 300Mi
  requests:
    cpu: 100m
    memory: 300Mi

ingress:
  enabled: true
  path: /oauth2
  hosts:
    - oauth2.hackathon.marthy.xyz
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-buffer-size: "8k"
  tls:
    - secretName: oauth2-hackathon-marthy-xyz
      hosts:
        - oauth2.hackathon.marthy.xyz