apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: babybuddy-db
spec:
  target:
    name: babybuddy-db
    creationPolicy: Owner
    template:
      metadata:
        labels:
          cnpg.io/reload: "true"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  data:
    - secretKey: DB_USER
      remoteRef:
        key: secret/general
        property: DB_USERNAME
    - secretKey: DB_PASSWORD
      remoteRef:
        key: secret/general
        property: DB_PASSWORD
