defaultNamespace: ingress-nginx
dependsOn:
  - name: rancher-charts-fleet-rancher-charts-01-monitoring
  - name: infra-fleet-infra-metallb
helm:
  releaseName: ingress-nginx
  chart: ingress-nginx
  repo: https://kubernetes.github.io/ingress-nginx
  version: 4.4.2
  values:
    controller:
      kind: DaemonSet
      service:
        externalTrafficPolicy: "Local"
        annotations:
          metallb.universe.tf/allow-shared-ip: ingress-nginx
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
          scrapeInterval: 15s
      ingressClassResource:
        default: true
targetCustomizations:
- name: sm5
  clusterSelector:
    matchLabels:
      provider.cattle.io: k3s
      topology.kubernetes.io/region: budapest
      topology.kubernetes.io/zone: sm5
  helm:
    valuesFiles:
      - sm5.yaml