defaultNamespace: ingress-nginx
dependsOn:
  - name: rancher-charts-fleet-rancher-charts-01-crd-monitoring
  - name: infra-fleet-infra-metallb
helm:
  releaseName: ingress-nginx
  chart: ingress-nginx
  repo: https://kubernetes.github.io/ingress-nginx
  version: 4.15.1
  valuesFiles:
  - global-values.yaml
targetCustomizations:
- name: oci
  clusterSelector:
    matchLabels:
      provider.cattle.io: k3s
      topology.kubernetes.io/region: eu-frankfurt-1
  helm:
    valuesFiles:
      - oci.yaml
- name: nas
  clusterSelector:
    matchLabels:
      provider.cattle.io: k3s
      topology.kubernetes.io/region: pecs
      topology.kubernetes.io/zone: nas
  helm:
    valuesFiles:
      - nas.yaml
- name: nuc
  clusterSelector:
    matchLabels:
      provider.cattle.io: k3s
      topology.kubernetes.io/region: budapest
      topology.kubernetes.io/zone: nuc
  helm:
    valuesFiles:
      - nuc.yaml