defaultNamespace: ingress-nginx
dependsOn:
  - name: rancher-charts-fleet-rancher-charts-01-monitoring
  - name: infra-fleet-infra-metallb
helm:
  releaseName: ingress-nginx
  chart: ingress-nginx
  repo: https://kubernetes.github.io/ingress-nginx
  version: 4.2.5
  values:
    controller:
      kind: DaemonSet
      service:
        externalTrafficPolicy: "Local"
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
          scrapeInterval: 15s
