defaultNamespace: ingress-nginx
dependsOn:
  - name: rancher-charts-fleet-rancher-charts-01-monitoring
  - name: infra-fleet-infra-metallb
helm:
  releaseName: ingress-nginx
  chart: ingress-nginx
  repo: https://kubernetes.github.io/ingress-nginx
  version: 4.10.2
  valuesFiles:
  - global-values.yaml
targetCustomizations:
- name: sm5
  clusterSelector:
    matchLabels:
      provider.cattle.io: k3s
      topology.kubernetes.io/region: budapest
      topology.kubernetes.io/zone: sm5
  helm:
    valuesFiles:
      - sm5.yaml
- name: nas
  clusterSelector:
    matchLabels:
      provider.cattle.io: k3s
      topology.kubernetes.io/region: pecs
      topology.kubernetes.io/zone: nas
  helm:
    valuesFiles:
      - nas.yaml
- name: rke2-1
  clusterSelector:
    matchLabels:
      provider.cattle.io: rke2
      topology.kubernetes.io/region: budapest
      topology.kubernetes.io/zone: esxi-sm1
      topology.kubernetes.io/cluster: rke2-1
  helm:
    valuesFiles:
      - rke2-1.yaml
- name: rke2-2
  clusterSelector:
    matchLabels:
      provider.cattle.io: rke2
      topology.kubernetes.io/region: budapest
      topology.kubernetes.io/zone: esxi-sm4
      topology.kubernetes.io/cluster: rke2-2
  helm:
    valuesFiles:
      - rke2-2.yaml