defaultNamespace: ingress-nginx
helm:
  releaseName: ingress-nginx
  chart: ingress-nginx
  repo: https://kubernetes.github.io/ingress-nginx
  values:
    controller:
      kind: DaemonSet
      service:
        externalTrafficPolicy: "Local"
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
          scrapeInterval: 15s
