controller:
  kind: DaemonSet
  service:
    annotations:
      metallb.universe.tf/allow-shared-ip: ingress-nginx
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      scrapeInterval: 15s
  ingressClassResource:
    default: true