controller:
  service:
    annotations:
      metallb.universe.tf/allow-shared-ip: ingress-nginx
      metallb.universe.tf/loadBalancerIPs: 192.168.11.1
    type: ClusterIP
  config:
    allow-snippet-annotations: "true"
  hostPort:
    enabled: true