apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  target:
    name: cloudflare-api-token
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  data:
  - remoteRef:
      key: secret/cloudflare
      property: api_token
    secretKey: api_token
