apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: route53-awssecret
  namespace: cert-manager
spec:
  target:
    name: route53-awssecret
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  data:
  - secretKey: aws_ak
    remoteRef:
      key: secret/cert-manager-budapest
      property: aws_ak
  - secretKey: aws_sk
    remoteRef:
      key: secret/cert-manager-budapest
      property: aws_sk