provider: aws

aws:
  credentials:
    accessKeyIDSecretRef:
      name: aws-cred
      key: aws_ak
    secretAccessKeySecretRef:
      name: aws-cred
      key: aws_sk
  zoneType: public
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
crd:
  create: true
