provider: aws

serviceMonitor:
    enabled: true

env:
  - name: AWS_DEFAULT_REGION
    value: us-east-1 
  - name: AWS_ACCESS_KEY_ID
    valueFrom:
      secretKeyRef:
        name: aws-cred
        key: aws_ak
  - name: AWS_SECRET_KEY
    valueFrom:
      secretKeyRef:
        name: aws-cred
        key: aws_sk
