ingress:
  main:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    enabled: true
    hosts:
    - host: radarr.tl.dr
      paths:
      - path: /
        pathType: Prefix
    ingressClassName: nginx
    tls:
    - hosts:
      - radarr.tl.dr
      secretName: radarr-tls
podSecurityContext:
  runAsUser: 568
  runAsGroup: 568
  fsGroup: 568
persistence:
  config:
    enabled: true
    type: pvc
    storageClass: ix-storage-class-radarr
  media:
    enabled: true
    type: hostPath
    hostPath: /zfs/media/movies
    mountPath: /media
metrics:
  enabled: true
  prometheusRule:
    enabled: true
  exporter:
    env:
      unknownQueueItems: true