apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: "https://vault.oci.marthy.xyz"
      path: "secret"
      version: "v2"
      auth:
        tokenSecretRef:
          key: token
          name: vault-oci-token
          namespace: external-secrets
