apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: "https://vault.oci.marthy.xyz"
      path: "secret"
      version: "v2"
      auth:
        appRole:
          path: "approle"
          roleId: "449c28a7-8dc6-5a49-65a9-e8faa70e0203"
          secretRef:
            name: "vault-oci-approle"
            key: "secret-id"
            namespace: external-secrets