ingress:
  main:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    enabled: true
    hosts:
    - host: jackett.tl.dr
      paths:
      - path: /
        pathType: Prefix
    ingressClassName: nginx
    tls:
    - hosts:
      - jackett.tl.dr
      secretName: jackett-tls
podSecurityContext:
  runAsUser: 568
  runAsGroup: 568
  fsGroup: 568
persistence:
  config:
    enabled: true
    type: pvc
    storageClass: ix-storage-class-jackett
  downloads:
    enabled: true
    type: hostPath
    hostPath: /zfs/media
    mountPath: /downloads
metrics:
  enabled: true
  prometheusRule:
    enabled: true
  exporter:
    env:
      unknownQueueItems: true