---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: clusterrepos
  namespace: fleet-default
spec:
  branch: main
  insecureSkipTLSVerify: false
  paths:
    - fleet/clusterrepos
  repo: https://github.com/marthydavid/homelab
  targets:
    - clusterSelector:
        matchExpressions:
          - key: provider.cattle.io
            operator: NotIn
            values:
              - harvester
