---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: infra
  namespace: fleet-default
spec:
  branch: main
  forceSyncGeneration: 18
  insecureSkipTLSVerify: false
  paths:
  - fleet/infra
  paused: false
  repo: https://github.com/marthydavid/homelab
  targets:
  - clusterSelector:
      matchLabels:
        provider.cattle.io: k3s
        topology.kubernetes.io/region: budapest
        topology.kubernetes.io/zone: rpi
    name: k3s
  - clusterSelector:
      matchLabels:
        provider.cattle.io: rke2
        topology.kubernetes.io/region: budapest
        topology.kubernetes.io/zone: esxi-hp
    name: rke2
  - clusterSelector:
      matchLabels:
        provider.cattle.io: k3s
        topology.kubernetes.io/region: budapest
        topology.kubernetes.io/zone: sm5
    name: sm5
  - name: nas
    clusterSelector:
      matchLabels:
        provider.cattle.io: k3s
        topology.kubernetes.io/region: pecs
        topology.kubernetes.io/zone: nas