---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: storage
  namespace: fleet-default
spec:
  branch: main
  insecureSkipTLSVerify: false
  paths:
  - fleet/storage
  paused: false
  repo: https://github.com/marthydavid/homelab
  targets:
  - clusterSelector:
      matchLabels:
        provider.cattle.io: rke2
        topology.kubernetes.io/region: budapest
        topology.kubernetes.io/zone: esxi-hp
    name: rke2