---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: truenas
  namespace: fleet-default
spec:
  branch: main
  forceSyncGeneration: 18
  insecureSkipTLSVerify: false
  paths:
  - fleet/truenas
  paused: false
  repo: https://github.com/marthydavid/homelab
  targets:
  - clusterSelector:
      matchLabels:
        provider.cattle.io: k3s
        topology.kubernetes.io/region: pecs
        topology.kubernetes.io/zone: nas
    name: nas
  - clusterSelector:
      matchLabels:
        provider.cattle.io: k3s
        topology.kubernetes.io/region: budapest
        topology.kubernetes.io/zone: sm5
    name: sm5