defaultNamespace: argocd
helm:
  releaseName: argocd
  chart: argo-cd
  repo: https://argoproj.github.io/argo-helm 
  version: 6.0.14
  valuesFiles:
    - global-values.yaml
dependsOn:
  - name: rancher-charts-fleet-rancher-charts-01-monitoring
