redis-ha:
  enabled: false

controller:
  replicas: 1

server:
  autoscaling:
    enabled: false
    minReplicas: 1
  ingress:
    # -- Enable an ingress resource for the Argo CD server
    enabled: true
    https: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      external-dns.alpha.kubernetes.io/target: pecs.marthy.xyz
      external-dns.alpha.kubernetes.io/alias: "true"
    ingressClassName: "nginx"
    hosts:
      - argocd.marthy.xyz
    tls:
      - secretName: argocd-server-tls
        hosts:
          - argocd.marthy.xyz

repoServer:
  autoscaling:
    enabled: false
    minReplicas: 1

applicationSet:
  replicaCount: 1


configs:
  cm:
    create: true
    url: "https://argocd.marthy.xyz"