redis-ha:
  enabled: false

controller:
  replicas: 1

server:
  autoscaling:
    enabled: false
    minReplicas: 1
  ingress:
    # -- Enable an ingress resource for the Argo CD server
    enabled: true
    https: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    ingressClassName: "nginx"
    hosts:
      - argo.budapest.marthy.xyz
    tls:
      - secretName: argo-budapest-tls
        hosts:
          - argo.budapest.marthy.xyz

repoServer:
  autoscaling:
    enabled: false
    minReplicas: 1

applicationSet:
  replicaCount: 1


configs:
  cm:
    create: true
    url: "https://argo.budapest.marthy.xyz"