kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: immich
  namespace: mediarr
spec:
  storageClassName: openebs-zfspv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 400Gi