---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 400Gi
  csi:
    driver: zfs.csi.openebs.io
    fsType: zfs
    volumeAttributes:
      openebs.io/poolname: zfs/media
    volumeHandle: immich
  persistentVolumeReclaimPolicy: Retain
  storageClassName: openebs-zfspv
  volumeMode: Filesystem
---
apiVersion: zfs.openebs.io/v1
kind: ZFSVolume
metadata:
  name: immich
  namespace: openebs
spec:
  capacity: "214748364800"
  fsType: zfs
  ownerNodeID: sm4.marthy.xyz
  poolName: zfs/media
  shared: "yes"
  volumeType: DATASET
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: immich
  namespace: mediarr
spec:
  storageClassName: openebs-zfspv
  volumeName: immich
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 400Gi