TZ: Europe/Budapest
docs:
  confirmDocs: true
global:
  isSCALE: true
  ixChartContext:
    isInstall: true
    isUpdate: false
    isUpgrade: false
    operation: INSTALL
    storageClassName: ix-storage-class-jackett
    upgradeMetadata: {}
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/jackett
ixChartContext:
  isInstall: true
  isUpdate: false
  isUpgrade: false
  operation: INSTALL
  storageClassName: ix-storage-class-jackett
  upgradeMetadata: {}
persistence:
  config:
    advanced: false
    enabled: true
    mountPath: /config
    readOnly: false
    type: simplePVC
podSecurityContext:
  fsGroup: 568
  fsGroupChangePolicy: OnRootMismatch
  runAsGroup: 568
  runAsUser: 568
  supplementalGroups: []
portal:
  enabled: true
probes:
  liveness:
    path: /UI/Login
  readiness:
    path: /UI/Login
  startup:
    path: /UI/Login
release_name: jackett
securityContext:
  readOnlyRootFilesystem: false
service:
  main:
    advancedsvcset: false
    enabled: true
    loadBalancerIP: ""
    ports:
      main:
        advanced: false
        port: 9117
        protocol: HTTP
        targetPort: 9117
    type: LoadBalancer
serviceexpert: false