defaultNamespace: chaos-mesh
dependsOn:
  - name: rancher-charts-fleet-rancher-charts-01-crd-monitoring
helm:
  releaseName: chaos-mesh
  chart: chaos-mesh
  repo: https://charts.chaos-mesh.org
  version: 2.6.4
  valuesFiles:
    - global-values.yaml
targetCustomizations:
  - name: nas
    clusterSelector:
      matchLabels:
        provider.cattle.io: k3s
        topology.kubernetes.io/region: pecs
        topology.kubernetes.io/zone: nas
    helm:
      valuesFiles:
        - nas.yaml
  - name: rpi
    clusterSelector:
      matchLabels:
        provider.cattle.io: k3s
        topology.kubernetes.io/region: budapest
        topology.kubernetes.io/zone: rpi
    helm:
      valuesFiles:
        - rpi.yaml
  - name: nuc
    clusterSelector:
      matchLabels:
        provider.cattle.io: rke2
        topology.kubernetes.io/region: budapest
        topology.kubernetes.io/zone: nuc
    helm:
      valuesFiles:
        - nuc.yaml