dashboard:
  enabled: true
  ingress:
    ## Set to true to enable ingress record generation
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      external-dns.alpha.kubernetes.io/alias: "true"
      external-dns.alpha.kubernetes.io/target: pecs.marthy.xyz
    hosts:
      - name: chaos.pecs.marthy.xyz
        tls: true
        tlsHosts:
          - chaos.pecs.marthy.xyz
        tlsSecret: chaos-nuc-tls
    ingressClassName: "nginx"
  securityMode: false