apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: plex-token
spec:
  target:
    name: plex-token
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  data:
  - secretKey: PLEX_TOKEN
    remoteRef:
      key: secret/general
      property: PLEX_TOKEN