apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: route53-awssecret
spec:
  data:
  - secretKey: aws_ak
    remoteRef:
      key: secret/cert-manager-pecs
      property: aws_ak
  - secretKey: aws_sk
    remoteRef:
      key: secret/cert-manager-pecs
      property: aws_sk
