apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ipmi-exporter-secret
  namespace: cattle-monitoring-system
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  data:
    - secretKey: config.yml
      remoteRef:
        key: secret/general
        property: ipmi_exporter_config


