defaultNamespace: crowdsec
dependsOn:
  - name: rancher-charts-fleet-rancher-charts-01-crd-monitoring
  - name: infra-fleet-infra-metallb
helm:
  releaseName: crowdsec
  chart: crowdsec
  repo: https://crowdsecurity.github.io/helm-charts
  version: 0.19.1
  valuesFiles:
  - global.yaml
targetCustomizations:
- name: oci
  clusterSelector:
    matchLabels:
      provider.cattle.io: k3s
      topology.kubernetes.io/region: eu-frankfurt-1
  helm:
    valuesFiles:
      - oci.yaml