lapi:
  dashboard:
    enabled: false
    ingress:
      enabled: true
      ingressClassName: "nginx"
      host: "crowdsec.oci.marthy.xyz"
      tls:
        - secretName: crowdsec-dashboard-tls
  env:
    - name: ENROLL_TAGS
      value: 'k8s linux oci'