defaultNamespace: metallb-system
dependsOn:
  - name: infra-fleet-infra-metallb
targetCustomizations:
- name: oci
  clusterSelector:
    matchLabels:
      provider.cattle.io: k3s
      topology.kubernetes.io/region: eu-frankfurt-1
  yaml:
    overlays:
      - oci
- name: nas
  clusterSelector:
    matchLabels:
      provider.cattle.io: k3s
      topology.kubernetes.io/region: pecs
      topology.kubernetes.io/zone: nas
  yaml:
    overlays:
      - nas
- name: rke2-1
  clusterSelector:
    matchLabels:
      provider.cattle.io: rke2
      topology.kubernetes.io/region: budapest
      topology.kubernetes.io/zone: esxi-sm1
      topology.kubernetes.io/cluster: rke2-1
  yaml:
    overlays:
      - rke2-1
- name: rke2-2
  clusterSelector:
    matchLabels:
      provider.cattle.io: rke2
      topology.kubernetes.io/region: budapest
      topology.kubernetes.io/zone: esxi-sm4
      topology.kubernetes.io/cluster: rke2-2
  yaml:
    overlays:
      - rke2-2
- name: k3s
  clusterSelector:
    matchLabels:
      provider.cattle.io: k3s
      topology.kubernetes.io/region: budapest
      topology.kubernetes.io/zone: rpi
  yaml:
    overlays:
      - k3s
- name: nuc
  clusterSelector:
    matchLabels:
      provider.cattle.io: k3s
      topology.kubernetes.io/region: budapest
      topology.kubernetes.io/zone: nuc
  yaml:
    overlays:
      - nuc
- name: sm5
  clusterSelector:
    matchLabels:
      provider.cattle.io: k3s
      topology.kubernetes.io/region: budapest
      topology.kubernetes.io/zone: sm5
  yaml:
    overlays:
      - sm5
