defaultNamespace: metallb-system
dependsOn:
  - name: infra-fleet-infra-metallb
targetCustomizations:
- name: nas
  clusterSelector:
    matchLabels:
      provider.cattle.io: k3s
      topology.kubernetes.io/region: pecs
      topology.kubernetes.io/zone: nas
  yaml:
    overlays:
      - nas
- name: rke2
  clusterSelector:
    matchLabels:
      provider.cattle.io: rke2
      topology.kubernetes.io/region: budapest
      topology.kubernetes.io/zone: esxi-hp
  yaml:
    overlays:
      - rke2
- name: k3s
  clusterSelector:
    matchLabels:
      provider.cattle.io: k3s
      topology.kubernetes.io/region: budapest
      topology.kubernetes.io/zone: rpi
  yaml:
    overlays:
      - k3s
- name: sm5
  clusterSelector:
    matchLabels:
      provider.cattle.io: k3s
      topology.kubernetes.io/region: budapest
      topology.kubernetes.io/zone: sm5
  yaml:
    overlays:
      - sm5
