defaultNamespace: metallb-system
dependsOn:
  - name: infra-fleet-infra-metallb
targetCustomizations:
- name: oci
  clusterSelector:
    matchLabels:
      provider.cattle.io: k3s
      topology.kubernetes.io/region: eu-frankfurt-1
  yaml:
    overlays:
      - oci
- name: nas
  clusterSelector:
    matchLabels:
      provider.cattle.io: k3s
      topology.kubernetes.io/region: pecs
      topology.kubernetes.io/zone: nas
  yaml:
    overlays:
      - nas
