installCRDs: true
serviceMonitor:
  enabled: true
webhook:
  serviceMonitor:
    enabled: true
certController:
  serviceMonitor:
    enabled: true
dashboard:
  enabled: true
  ingress:
    ## Set to true to enable ingress record generation
    enabled: true
  securityMode: false