global:
  fullnameOverride: ddns-route53
image:
  repository: crazymax/ddns-route53
  tag: 2.10.0


env:
  - name: TZ
    value: Europe/Budapest
  - name: LOG_JSON
    value: "false"
  - name: LOG_LEVEL
    value: info
  - name: MAX_RETRIES
    value: "3"
  - name: SCHEDULE
    value: '*/5 * * * *'

envFrom:
  - secretRef:
      name: ddns-route53-credentials
  - configMapRef:
      name: ddns-route53-config

service:
  main:
    enabled: false