alertmanager:
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/auth-signin: https://oauth2.pecs.marthy.xyz/oauth2/start?rd=$scheme://$best_http_host$request_uri
      nginx.ingress.kubernetes.io/auth-url: https://oauth2.pecs.marthy.xyz/oauth2/auth
    enabled: true
    ingressClassName: nginx
    hosts:
      - alert.pecs.marthy.xyz
    tls:
      - secretName: alertmanager-tls-secret
        hosts:
          - alert.pecs.marthy.xyz
  config:
    global:
      slack_api_url: https://hooks.slack.com/services/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
    route:
      receiver: "slack"
      group_by:
        - job
        - alertname
        - stage
        - severity
        - app
      routes:
        - matchers:
            - alertname="Watchdog"
          receiver: "slack"
          continue: true
        - matchers:
            - severity="Critical"
          receiver: "slack"
          continue: true
        - matchers:
            - severity="Warning"
          receiver: "slack"
          continue: true
    receivers:
      - name: "slack"
        slack_configs:
          - send_resolved: true
prometheus:
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/auth-signin: https://oauth2.pecs.marthy.xyz/oauth2/start?rd=$scheme://$best_http_host$request_uri
      nginx.ingress.kubernetes.io/auth-url: https://oauth2.pecs.marthy.xyz/oauth2/auth
    enabled: true
    ingressClassName: nginx
    hosts:
      - prom.pecs.marthy.xyz
    tls:
      - secretName: prometheus-tls-secret
        hosts:
          - prom.pecs.marthy.xyz
  prometheusSpec:
    resources:
      limits:
        cpu: 500m
        memory: 2Gi
      requests:
        cpu: 100m
        memory: 100Mi
    retention: 100d
    retentionSize: 45GiB
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: openebs-zfspv
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 100Gi