alertmanager:
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    enabled: true
    ingressClassName: nginx
    hosts:
      - alert.hackathon.marthy.xyz
    tls:
      - secretName: alertmanager-tls-secret
        hosts:
          - alert.hackathon.marthy.xyz
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        metadata:
          name: rancher-alertmanager
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 1Gi
prometheus:
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    enabled: true
    ingressClassName: nginx
    hosts:
      - prom.hackathon.marthy.xyz
    tls:
      - secretName: prometheus-tls-secret
        hosts:
          - prom.hackathon.marthy.xyz
  prometheusSpec:
    resources:
      limits:
        cpu: 500m
        memory: 2Gi
      requests:
        cpu: 100m
        memory: 100Mi
    retention: 100d
    retentionSize: 45GiB
    storageSpec:
      volumeClaimTemplate:
        metadata:
          name: rancher-prometheus
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 20Gi
