ingress:
  main:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    enabled: true
    hosts:
    - host: sonarr.tl.dr
      paths:
      - path: /
        pathType: Prefix
    ingressClassName: nginx
    tls:
    - hosts:
      - sonarr.tl.dr
      secretName: sonarr-tls
persistence:
  config:
    enabeld: true
    type: pvc
    storageClass: ix-storage-class-sonarr
  media:
    enabled: true
    type: hostPath
    hostPath: /mnt/zfs/media/series
    mountPath: /media
metrics:
  enabled: true
  prometheusRule:
    enabled: true
  exporter:
    env:
      unknownQueueItems: true