defaultNamespace: metallb-system
helm:
  releaseName: metallb
  chart: metallb
  repo: https://metallb.github.io/metallb
  version: v0.13.4
  valuesFiles:
    - global.yaml
dependsOn:
  - name: rancher-charts-fleet-rancher-charts-01-monitoring
targetCustomizations:
- name: k3s
  clusterSelector:
    matchLabels:
      provider.cattle.io: k3s
      topology.kubernetes.io/region: budapest
      topology.kubernetes.io/zone: rpi
  helm:
    valuesFiles:
      - k3s.yaml
- name: rke2
  clusterSelector:
    matchLabels:
      provider.cattle.io: rke2
      topology.kubernetes.io/region: budapest
      topology.kubernetes.io/zone: esxi-hp
  helm:
    valuesFiles:
      - rke2.yaml
