defaultNamespace: metallb-system
helm:
  releaseName: metallb
  chart: metallb
  repo: https://metallb.github.io/metallb
  version: v0.12.1
  valuesFiles:
    - global.yaml
dependsOn:
  - name: rancher-charts-fleet-rancher-charts-01-monitoring