defaultNamespace: metallb-system
helm:
  releaseName: metallb
  chart: metallb
  repo: https://metallb.github.io/metallb
  version: 0.15.2
  valuesFiles:
    - global-values.yaml
dependsOn:
  - name: rancher-charts-fleet-rancher-charts-01-crd-monitoring
diff:
  comparePatches:
  # - apiVersion: apiextensions.k8s.io/v1
  #   kind: CustomResourceDefinition
  #   name: addresspools.metallb.io
  #   operations:
  #   - {"op":"remove", "path":"/spec/conversion/webhook/clientConfig/caBundle"}
  #   - {"op":"remove", "path":"/status"}
  # - apiVersion: apiextensions.k8s.io/v1
  #   kind: CustomResourceDefinition
  #   name: bgppeers.metallb.io
  #   operations:
  #   - {"op":"remove", "path":"/spec/conversion/webhook/clientConfig/caBundle"}
  #   - {"op":"remove", "path":"/status"}
  - apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: bgppeers.metallb.io
    jsonPointers:
    - "/spec/conversion/webhook/clientConfig/caBundle"
    - "/spec/conversion/webhook"
targetCustomizations:
- name: oci
  clusterSelector:
    matchLabels:
      provider.cattle.io: k3s
      topology.kubernetes.io/region: eu-frankfurt-1
  helm:
    valuesFiles:
      - oci.yaml