defaultNamespace: metallb-system
helm:
  releaseName: metallb
  chart: metallb
  repo: https://metallb.github.io/metallb
  version: 0.13.10
  valuesFiles:
    - global-values.yaml
dependsOn:
  - name: rancher-charts-fleet-rancher-charts-01-monitoring
diff:
  comparePatches:
  - apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: addresspools.metallb.io
    operations:
    - {"op":"remove", "path":"/spec/conversion/webhook/clientConfig/caBundle"}
    - {"op":"remove", "path":"/status"}
  - apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: bgppeers.metallb.io
    operations:
    - {"op":"remove", "path":"/spec/conversion/webhook/clientConfig/caBundle"}
    - {"op":"remove", "path":"/status"}