prometheus:
  serviceAccount: rancher-monitoring-prometheus
  namespace: cattle-monitoring-system
  podMonitor:
    enabled: true
  prometheusRule:
    enabled: true
speaker:
  frr:
    enabled: true
