configInline:
  address-pools:
  - addresses:
    - 192.168.12.2-192.168.12.10
    avoid-buggy-ips: true
    name: default
    protocol: bgp
  peers:
  - my-asn: 65530
    peer-address: 192.168.10.254
    peer-asn: 65530
