configInline:
  address-pools:
  - addresses:
    - 192.168.12.12-192.168.12.20
    avoid-buggy-ips: true
    name: default
    protocol: bgp
  peers:
  - my-asn: 65530
    peer-address: 192.168.10.254
    peer-asn: 65530
speaker:
  frr:
    enabled: true
    logLevel: informational
    image:
      repository: quay.io/frrouting/frr
      tag: stable_7.5