apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ipmi-secret
spec:
  target:
    name: ipmi-secret
    creationPolicy: Owner
    template:
      metadata:
        labels:
          cnpg.io/reload: "true"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  data:
    - secretKey: username
      remoteRef:
        key: secret/general
        property: DB_USERNAME
    - secretKey: password
      remoteRef:
        key: secret/general
        property: DB_PASSWORD
