# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: database
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:14.8-7
  primaryUpdateStrategy: unsupervised
  storage:
    size: 20Gi
    storageClass: openebs-zfspv
  superuserSecret:
    name: cloudnative-pg-secret
  postgresql:
    parameters:
      max_connections: "600"
      shared_buffers: 512MB
      timezone: "Europe/Budapest"
  monitoring:
    enablePodMonitor: true