TZ: Europe/Budapest
global:
  isSCALE: true
  ixChartContext:
    isInstall: true
    isUpdate: false
    isUpgrade: false
    operation: UPDATE
    storageClassName: ix-storage-class-qbit
    upgradeMetadata: {}
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/qbittorrent
ixChartContext:
  isInstall: true
  isUpdate: false
  isUpgrade: false
  operation: INSTALL
  storageClassName: ix-storage-class-qbit
  upgradeMetadata: {}
persistence:
  config:
    advanced: false
    enabled: true
    mountPath: /config
    readOnly: false
    type: simplePVC
podSecurityContext:
  fsGroup: 568
  fsGroupChangePolicy: OnRootMismatch
  runAsGroup: 568
  runAsUser: 568
  supplementalGroups: []
portal:
  enabled: true
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    add: []
    drop: []
  privileged: false
  readOnlyRootFilesystem: false
  runAsNonRoot: true
service:
  main:
    enabled: true
    ipFamilies: []
    ipFamilyPolicy: SingleStack
    ports:
      main:
        advanced: false
        port: 10095
        targetPort: 8080
    type: ClusterIP
  torrent:
    enabled: true
    ports:
      torrent:
        advanced: false
        enabled: true
        port: 6881
        targetPort: 6881
    type: Simple
  torrentudp:
    enabled: true
    ports:
      torrentudp:
        advanced: false
        enabled: true
        port: 6881
        protocol: UDP
        targetPort: 6881
    type: Simple