---
#https://anywhere.eks.amazonaws.com/docs/tasks/workload/loadbalance/kubevip/bgp/
#https://github.com/k8s-at-home/template-cluster-k3s/blob/main/provision/ansible/playbooks/templates/kube-vip-daemonset.yaml.j2
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-vip-ds
spec:
  selector:
    matchLabels:
      name: kube-vip-ds
  template:
    metadata:
      labels:
        name: kube-vip-ds
    spec:
      containers:
      - name: kube-vip
        args:
        - manager
        env:
        image: ghcr.io/kube-vip/kube-vip:v0.6.4
        imagePullPolicy: IfNotPresent
        resources: {}
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
            - SYS_TIME
      hostNetwork: true
      serviceAccountName: kube-vip
  updateStrategy: {}
