apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: crowdsec-token
  namespace: crowdsec
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  data:
    - secretKey: ENROLL_KEY
      remoteRef:
        key: secret/crowdsec
        property: oci_enroll
    - secretKey: ENROLL_INSTANCE_NAME
      remoteRef:
        key: secret/crowdsec
        property: oci_enroll_instance

