apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: crowdsec-ingress
  namespace: ingress-nginx
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  data:
    - secretKey: API_KEY
      remoteRef:
        key: secret/crowdsec
        property: oci_ingress_bouncer

