    controller:
      type: cronjob
      cronjob:
        # -- Specifies how to treat concurrent executions of a job that is created by this cron job
        # valid values are Allow, Forbid or Replace
        concurrencyPolicy: Forbid
        # -- Sets the CronJob time when to execute your jobs
        schedule: "10 */2 * * *"
    image:
      repository: ghcr.io/marthydavid/supermicro-letsencrypt
      tag: v0.2.0
      pullPolicy: IfNotPresent
    securityContext:
      runAsUser: 1000
    service:
      main:
        enabled: false

    ingress:
      main:
        enabled: false

    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: false

    persistence:
      lego:
        enabled: true
        hostPath: /zfs/k3s/configs/sm-lego
        mountPath: /home/lego/.lego
        type: hostPath