TZ: Europe/Budapest
env:
  LOG_LEVEL: info
global:
  isSCALE: true
  ixChartContext:
    isInstall: false
    isUpdate: false
    isUpgrade: true
    operation: UPGRADE
    storageClassName: ix-storage-class-overseerr
    upgradeMetadata:
      newChartVersion: 6.0.33
      oldChartVersion: 6.0.32
      preUpgradeRevision: 6
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/overseerr
ixChartContext:
  isInstall: false
  isUpdate: false
  isUpgrade: true
  operation: INSTALL
  storageClassName: ix-storage-class-overseerr
  upgradeMetadata: {}
persistence:
  config:
    advanced: false
    enabled: true
    mountPath: /app/config
    readOnly: false
    type: simplePVC
portal:
  enabled: true
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    add: []
    drop: []
  privileged: false
  readOnlyRootFilesystem: false
  runAsNonRoot: true
service:
  main:
    advancedsvcset: false
    enabled: true
    ipFamilies: []
    ipFamilyPolicy: SingleStack
    ports:
      main:
        advanced: false
        port: 5055
        targetPort: 5055
    type: ClusterIP