ingress:
  main:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    enabled: true
    hosts:
    - host: overseerr.tl.dr
      paths:
      - path: /
        pathType: Prefix
    ingressClassName: nginx
    tls:
    - hosts:
      - overseerr.tl.dr
      secretName: overseerr-tls
podSecurityContext:
  runAsUser: 568
  runAsGroup: 568
  fsGroup: 568
persistence:
  config:
    enabled: true
    type: pvc
    storageClass: ix-storage-class-overseerr
metrics:
  enabled: true
  prometheusRule:
    enabled: true
  exporter:
    env:
      unknownQueueItems: true