defaultNamespace: crowdsec
dependsOn:
  - name: global-apps-fleet-global-apps-external-secrets
targetCustomizations:
- name: oci
  clusterSelector:
    matchLabels:
      provider.cattle.io: k3s
      topology.kubernetes.io/region: eu-frankfurt-1
  yaml:
    overlays:
      - oci