apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ipmi-secret
spec:
  target:
    name: ipmi-secret
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  data:
  - secretKey: AWS_ACCESS_KEY_ID
    remoteRef:
      key: secret/cert-manager-pecs
      property: aws_ak
  - secretKey: AWS_SECRET_ACCESS_KEY
    remoteRef:
      key: secret/cert-manager-pecs
      property: aws_sk
  - secretKey: IPMI_PASSWORD
    remoteRef:
      key: secret/general
      property: IPMI_PASSWORD