---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: own-networks
  labels:
    app: prometheus-blackbox-exporter
spec:
  endpoints:
  - port: probe
    scheme: http
    path: "/probe"
    params:
      module:
      - icmp
      target:
      - 192.168.1.30
    metricRelabelings:
      - targetLabel: instance
        replacement: 192.168.1.30
      - targetLabel: target
        replacement: prometheus-blackbox-exporter
  - port: probe
    scheme: http
    path: "/probe"
    params:
      module:
      - icmp
      target:
      - 192.168.0.1
    metricRelabelings:
      - targetLabel: instance
        replacement: 192.168.0.1
      - targetLabel: target
        replacement: prometheus-blackbox-exporter
  - port: probe
    scheme: http
    path: "/probe"
    params:
      module:
      - icmp
      target:
      - 192.168.0.254
    metricRelabelings:
      - targetLabel: instance
        replacement: 192.168.0.254
      - targetLabel: target
        replacement: prometheus-blackbox-exporter
  - port: probe
    scheme: http
    path: "/probe"
    params:
      module:
      - icmp
      target:
      - 192.168.10.20
    metricRelabelings:
      - targetLabel: instance
        replacement: 192.168.10.20
      - targetLabel: target
        replacement: prometheus-blackbox-exporter
  - port: probe
    scheme: http
    path: "/probe"
    params:
      module:
      - icmp
      target:
      - 1.0.0.1
    metricRelabelings:
      - targetLabel: instance
        replacement: 1.0.0.1
      - targetLabel: target
        replacement: prometheus-blackbox-exporter
  jobLabel: prometheus-blackbox-exporter
  selector:
    matchLabels:
      release: prometheus-blackbox-exporter
